# Generated by Django 4.2.5 on 2023-09-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appplayerstats',
            name='game_id',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='app.appgame'),
        ),
        migrations.AlterField(
            model_name='appplayerstats',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='app.appplayer'),
        ),
    ]
